language: python

dist: bionic
sudo: required

addons:
  apt:
    packages:
    - graphviz

# https://docs.travis-ci.com/user/languages/python/
python:
- "2.7"
- "3.6"
- "3.7"

script:
- python tests/test.py
