name: testOnly
  #  This is a workflow that only does tests; a different workflow does
  #  tests and build

on:
  push:
    paths:
      - .github/workflows/testOnly.yml
  workflow_dispatch:
  #  manual launch only

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.12']  # oldest and youngest Pythons alive
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: sudo apt-get update -qq
      - run: sudo apt-get install -qq -y --no-install-recommends graphviz
      - run: python --version
      - run: python -m pip install --upgrade pip setuptools wheel

      # using --max-acceptable to reject tests if more error  happen.
      #   Setting this parameter allows tests to be more stringent than those in
      #       workflow  'build.yml'
      - run: python tests/test.py --max-acceptable=0
